version: '3'

services:

  node:
    build:
      context: node
    container_name: node
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 120s node index.js
    networks:
      - node-mysql-nginx-network
    tty: true
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=desafio
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    networks:
      - node-mysql-nginx-network

  nginx:
    build:
      context: nginx
    container_name: nginx
    depends_on:
      - node
    networks:
      - node-mysql-nginx-network
    ports:
      - "8080:80"

networks:
  node-mysql-nginx-network:
    driver: bridge